apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: tazamaorg/admin-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
          envFrom:
            - configMapRef:
                name: admin-env
            - configMapRef:
                name: tazama-global-env
          env:
            - name: CONFIGURATION_DATABASE_USER
              value: postgres
            - name: CONFIGURATION_DATABASE_PASSWORD
              value: unused
            - name: EVENT_HISTORY_DATABASE_USER
              value: postgres
            - name: EVENT_HISTORY_DATABASE_PASSWORD
              value: unused
            - name: EVALUATION_DATABASE_USER
              value: postgres
            - name: EVALUATION_DATABASE_PASSWORD
              value: unused
          readinessProbe:
            tcpSocket:
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - port: 3100
      targetPort: 3100
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms
  template:
    metadata:
      labels:
        app: tms
    spec:
      containers:
        - name: tms
          image: tazamaorg/tms-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: tms-env
            - configMapRef:
                name: tazama-global-env
          env:
            - name: EVENT_HISTORY_DATABASE_USER
              value: postgres
            - name: EVENT_HISTORY_DATABASE_PASSWORD
              value: unused
            - name: RAW_HISTORY_DATABASE_USER
              value: postgres
            - name: RAW_HISTORY_DATABASE_PASSWORD
              value: unused
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tms
spec:
  selector:
    app: tms
  ports:
    - port: 3000
      targetPort: 3000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ed
  template:
    metadata:
      labels:
        app: ed
    spec:
      containers:
        - name: ed
          image: tazamaorg/event-director
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ed-env
            - configMapRef:
                name: tazama-global-env
          env:
            - name: CONFIGURATION_DATABASE_USER
              value: postgres
            - name: CONFIGURATION_DATABASE_PASSWORD
              value: unused
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp
  template:
    metadata:
      labels:
        app: tp
    spec:
      containers:
        - name: tp
          image: tazamaorg/typology-processor
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: tp-env
            - configMapRef:
                name: tazama-global-env
          env:
            - name: CONFIGURATION_DATABASE_USER
              value: postgres
            - name: CONFIGURATION_DATABASE_PASSWORD
              value: unused
            - name: SUPPRESS_ALERTS
              value: "false"
            - name: INTERDICTION_DESTINATION
              value: global
            - name: INTERDICTION_PRODUCER
              value: interdiction-service-tp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tadp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tadp
  template:
    metadata:
      labels:
        app: tadp
    spec:
      containers:
        - name: tadp
          image: tazamaorg/transaction-aggregation-decisioning-processor
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: tadp-env
            - configMapRef:
                name: tazama-global-env
          env:
            - name: CONFIGURATION_DATABASE_USER
              value: postgres
            - name: CONFIGURATION_DATABASE_PASSWORD
              value: unused
            - name: RAW_HISTORY_DATABASE_USER
              value: postgres
            - name: RAW_HISTORY_DATABASE_PASSWORD
              value: unused
            - name: EVALUATION_DATABASE_USER
              value: postgres
            - name: EVALUATION_DATABASE_PASSWORD
              value: unused
            - name: SUPPRESS_ALERTS
              value: "false"
            - name: ALERT_DESTINATION
              value: global
            - name: ALERT_PRODUCER
              value: investigation-service
            - name: ALERTS_ONLY
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ef
  template:
    metadata:
      labels:
        app: ef
    spec:
      containers:
        - name: ef
          image: tazamaorg/event-flow
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: event-flow-env
            - configMapRef:
                name: tazama-global-env
          env:
            - name: CONFIGURATION_DATABASE_USER
              value: postgres
            - name: CONFIGURATION_DATABASE_PASSWORD
              value: unused
            - name: SUPPRESS_ALERTS
              value: "false"
            - name: INTERDICTION_DESTINATION
              value: global
            - name: INTERDICTION_PRODUCER
              value: interdiction-service-ef
